// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationEPFO.Models;

#nullable disable

namespace WebApplicationEPFO.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20240820104031_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationEPFO.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("WebApplicationEPFO.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("Departmentid")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Designation ");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("Departmentid");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("WebApplicationEPFO.Models.Employee", b =>
                {
                    b.HasOne("WebApplicationEPFO.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Departmentid")
                        .HasConstraintName("fk_emp_dept");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebApplicationEPFO.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
